### ISSUE TITLE
find_package()

### ISSUE THREAD

**Issue by feresr** [skypjack/homebrew-entt#1]
Hi, I'd like to import `entt` as I import the rest of my libraries. 
I've installed using homebrew.
Unfortunately `find_package(entt REQUIRED)` throws

```
CMake Error at engine/CMakeLists.txt:5 (find_package):
  By not providing "Findentt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "entt", but
  CMake did not find one.
```

I apologize in advance if this is a dumb question, I'm just getting started with C++/Cmake and it's hard to find good documentation. This method has been working for me in libraries like glfw3 and assimp

**Comment by skypjack** [comment]
Uhm... dunno how homebrew works exactly. Maybe @Kerndog73 who initiated this repo can help?

**Comment by indianakernick** [comment]
Well, I dunno how `find_package` works...

**Comment by feresr** [comment]
LOL that makes three of us. Thanks for your time anyways, I went with just adding the single header file into my project and it's working now. The reason I wanted to use `find_package` was to keep some level of consistency when adding libraries to my project. I gues I'm not going to be so lucky

**Comment by skypjack** [comment]
You don't have to find EnTT as in `find_package` btw, just `add_directory` it and you'll be able to link your target to `EnTT::EnTT`.
